### ISSUE TITLE
Enhancement: Add brightness control

### ISSUE THREAD

**Issue by Kosm925** [ShaunPrice/FSEQLib#1]
at setup initialize brightness control, something like;

//FastLED initialize LED brightness (0 = Low, 255 = High):
  FastLED.setBrightness(255);

**Comment by ShaunPrice** [comment]
I've updated the example with this code to set the global brightness. I also also added notes around not using it as the first choice. The brightness should be set in Xlights where possible to ensure the display is consistent.
