### ISSUE TITLE
Can't Compile example for WeMos R1D1 in arduino

### ISSUE THREAD

**Issue by sydkahn** [ShaunPrice/FSEQLib#3]
can't compile example compile throws an error: no matching function for call to 'SDClass::begin()'

[stacktrace.txt](https://github.com/ShaunPrice/FSEQLib/files/3809340/stacktrace.txt)
using arduino 1.8.10
trying to compile for board WeMos D1 R1
have defined #define ESP8266 0
compiler messages says:
Using library SD at version 2.0.0 in folder: C:\Users\loft\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\SD 

[stacktrace.txt](https://github.com/ShaunPrice/FSEQLib/files/3809341/stacktrace.txt)

**Comment by ShaunPrice** [comment]
I can confirm that there is an issue but it appears that something changed in the esp8266 libraries. Unfortunately I don't have the time at the moment to debug the issues to find out what changed. If it's still an issue next year I'll see if I can make any updates required. In the meantime you could compile it by loading up an older version of the Arduino compiler and esp8266 libraries.

**Comment by ShaunPrice** [comment]
I may have found the issue but the code has not been tested. I've added an updated example in the ESP8266_ SdFat branch. The SD and FS libraries were merged into the SdFat library.
Please try this and let me know if it works.
This is a direct link to the updated example:
https://github.com/ShaunPrice/FSEQLib/tree/ESP8266_SdFat/examples/FSEQPlayer

**Comment by sydkahn** [comment]
I tried your fix - it compiles and uploads - but doesn't work - I tried turning on debug mode - but nothing came out on the serial line....

I used arduino 1.8.100 - My prefered development IDE is Platform IO running in Visual Studio Code ..  Tried that but still no joy ...

Is there a possibility of getting the binary file to flash the chip???

**Comment by ShaunPrice** [comment]
I found the issue in that the SD card begin function was updated in the current libraries and now requires the SS pin number as a parameter.

Line 136 `SD.begin(SS)`
