### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by dallen98** [ShaunPrice/FSEQLib#5]
Hello shaun I have today placed your code into my arduino ide v 1.8.12 selected  ESP32 dev module and get ...
'class SdFat' has no member named 'end'

I then select  Generic ESP8266 module and get...
'D2' was not declared in this scope
on line 63, any ideas or remedies ? Thanks

**Comment by dallen98** [comment]
since writing above i have just updated SdFat by Bill Greiman to version 2.01, i then select nodemcu 0.9 (ESP-12 Module) and this now compiles however when I try to compile with ESP Dev module, ESP32 Wrover, NODE32s, NODEMCU-32s I still get this error....
'SdFat {aka class SdFat32}' has no member named 'end'
Which boards should I be choosing ? Thanks

**Comment by ShaunPrice** [comment]
You might have an SD library issue. I just compiled it with the inbuilt SD library for the ESP32 Wrover without an issue. I would recommend removing the third party SD library or point to the standard libraries.

**Comment by dallen98** [comment]
i,m just trying this on a different windows10 pc with a new install of arduino ide 1.8.13 i get this output on the ide...

Arduino: 1.8.13 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

FSEQPlayer:42:19: fatal error: SdFat.h: No such file or directory

compilation terminated.

Multiple libraries were found for "FastLED.h"

 Used: C:\Users\PC\Documents\Arduino\libraries\FastLED

 Not used: C:\Users\PC\Documents\Arduino\libraries\FastLED8.1

exit status 1

SdFat.h: No such file or directory



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

I see in libraries manager several SdFat options to add to my library including SdFat by Bill Greiman to version 2.01, let me know which one Thanks Dave

**Comment by ShaunPrice** [comment]
Below is the software and library versions I'm using. I just checked and they're the latest versions.

Arduino 1.8.13
Espressif's ESP32 v1.0.4 - https://github.com/espressif/arduino-esp32
FastLED v3.3.3 (from http://fastled.io/) - https://github.com/FastLED/FastLED

The SD library is included in Espressif's installation.
The original FastLED from fastled.io is at version 3.3.3. A file saying FastLED8.1 appears to be the wrong library.

Let me know how you go.

**Comment by dallen98** [comment]
thanks for quick reply, my libraries are full of custom code so for the avoidance of doubt i,m going to match your above software on a third pc in the coming days and let you know cheers

**Comment by ShaunPrice** [comment]
You could also try PlatformIO. It has all the latest libraries and boards. I also I just uploaded FSEQLib to the platform. The libraries are per project so you'll have a clean build.

**Comment by ShaunPrice** [comment]
I just performed a successful end-to-end test using the example app on PlatformIO using a new Wemos Lolin32 dev board and the below config. I also tried the Arduino IDE with no issues. Try PlatformIO and let me know how you go.

[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino
lib_deps = 
	fastled/FastLED@^3.3.3
	shaunprice/FSEQLib@^1.1.1

**Comment by dallen98** [comment]
I have fresh installed onto win10 the arduino ide 1.8.13 and esp32 v1.04 and fastled v 3.3.3 and then selected wemos lolin32 and get...
SdFat.h: No such file or directory
I then repeat the above on win7 and get the same error, if you could suggest a way forward thanks

**Comment by ShaunPrice** [comment]
I found some issues in the headers again. It appears that the ESP8266 have reverted from SdFat to what they were previously.  I've updated the example in the latest release v1.1.2. I also found some other issues I fixed such as the pin reference was using aliases that weren't available to generic ESP8266's that I've now fixed.

Let me know how the new version goes.

**Comment by dallen98** [comment]
yes this now compiles/uploads on my esp32 wroom thankyou

**Comment by dallen98** [comment]
...and i now have this serial output, does it look ok ?

Buffer Failed to load. Closing File and SD card
Initializing SD card...card initialized.
File size: 7837
======================
== Xlights FSEQ Header
======================
Magic: PSEQ⸮
Data Offset: 148
Version: 2.0
Header Length: 112
Channels per Step: 768
Number of Steps: 600
Step Time (ms): 50
Universes: 2561
Size of Universe: N/A
Gamma: 16
Light Type: UNKNOWN
======================
done!
Buffer Failed to load. Closing File and SD card
Initializing SD card...card initialized.
File size: 7837
======================
== Xlights FSEQ Header
======================
Magic: PSEQ⸮
Data Offset: 148
Version: 2.0
Header Length: 112
Channels per Step: 768
Number of Steps: 600
Step Time (ms): 50
Universes: 2561
Size of Universe: N/A
Gamma: 16
Light Type: UNKNOWN
======================
done!
Buffer Failed to load. Closing File and SD card
Initializing SD card...card initialized.
File size: 7837
======================
== Xlights FSEQ Header
======================
Magic: PSEQ⸮

**Comment by ShaunPrice** [comment]
Your buffer is to large. With 2561 universes and 768 channels you need a buffer of almost 2Mb. You would normally only have one universe. Look at the instructions on how to set up a universe in xlights. You should have a buffer under 1kb even if you're running 300 pixels.

**Comment by ShaunPrice** [comment]
Closing issue as it has been proven to work with correct data.

**Comment by ShaunPrice** [comment]
> Your buffer is to large. With 2561 universes and 768 channels you need a buffer of almost 2Mb. You would normally only have one universe. Look at the instructions on how to set up a universe in xlights. You should have a buffer under 1kb even if you're running 300 pixels.



> ...and i now have this serial output, does it look ok ?
> 
> # Buffer Failed to load. Closing File and SD card
> Initializing SD card...card initialized.
> File size: 7837
> # == Xlights FSEQ Header
> # Magic: PSEQ⸮
> Data Offset: 148
> Version: 2.0
> Header Length: 112
> Channels per Step: 768
> Number of Steps: 600
> Step Time (ms): 50
> Universes: 2561
> Size of Universe: N/A
> Gamma: 16
> Light Type: UNKNOWN
> # done!
> Buffer Failed to load. Closing File and SD card
> Initializing SD card...card initialized.
> File size: 7837
> # == Xlights FSEQ Header
> # Magic: PSEQ⸮
> Data Offset: 148
> Version: 2.0
> Header Length: 112
> Channels per Step: 768
> Number of Steps: 600
> Step Time (ms): 50
> Universes: 2561
> Size of Universe: N/A
> Gamma: 16
> Light Type: UNKNOWN
> # done!
> Buffer Failed to load. Closing File and SD card
> Initializing SD card...card initialized.
> File size: 7837
> # == Xlights FSEQ Header
> Magic: PSEQ⸮

I just had similar issues and noticed something in you file. It's version 2.0. The library was created for version 1.0 but it's been updated to v2.0 in xlights. I'll be fixing this over the next couple of days so it works with both versions.

**Comment by ShaunPrice** [comment]
Version-2.0.0 branch has been uploaded but requires more testing. A workaround is in the readme that requires the sequence preferences to be changed to save to FSEQ v1.0 file format by going to [File][Preferences] sequence tab and changing the FSEQ Version to V1.
