### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dallen98** [ShaunPrice/FSEQLib#6]
Can it stream from xlights using the glediator protocol ? (or any other protocol because I cant see glediator protocol being offered in xlights) I have the following code streaming from jinx into esp32.

#include "FastLED.h"
#define NUM_LEDS 400
const int dataline = 6;

CRGB leds[NUM_LEDS];
void setup() {
        Serial.begin(115200);
     LEDS.addLeds<WS2812B, dataline>(leds, NUM_LEDS);
}
int serialGlediator() {
  while (!Serial.available()) {}
  return Serial.read();
}
void loop() {
   while (serialGlediator() != 1) {}

   for (int i=0; i < NUM_LEDS; i++) {
     leds[i].r = serialGlediator();
     leds[i].g = serialGlediator();
     leds[i].b = serialGlediator();
   }
     FastSPI_LED.show();
}

**Comment by ShaunPrice** [comment]
This project is just an example for the Xlights file format (FSEQ) so it can be played directly on an ESP device. I have another project called PixelMagic that's almost finished but not public yet that takes streaming data in e.131 format over WiFi from Xlights and displays it. I'll see what I can do to get an early beta version up in the next few days.

**Comment by dallen98** [comment]
Looking forward to it thanks
