### ISSUE TITLE
Buffer Fail

### ISSUE THREAD

**Issue by harueg** [ShaunPrice/FSEQLib#8]
Hi @ShaunPrice 

Wanted to try your software, but got stuck with :

Buffer failed to load :

Initializing SD card...
card initialized.
File size: 16068
======================
== Xlights FSEQ V2.0 Header
======================
Magic: PSEQ
Data Offset: 68
Version: 2.0
Header Length: 32
Channels per Step: 400
Number of Steps: 40
Step Time (ms)
: 25
Compression Type: Uncompressed
Compressed Blocks: 0
Sparse Ranges: 0
UUID: 
======================
done!
Buffer Failed to load. Closing File and SD card

Code :
[FSEQPlayer.ino.txt](https://github.com/ShaunPrice/FSEQLib/files/6141523/FSEQPlayer.ino.txt)

FSEQ File :
[test.led.txt](https://github.com/ShaunPrice/FSEQLib/files/6141546/test.led.txt)

`Thanks and best regard

Harald

**Comment by ShaunPrice** [comment]
Hi Harald,

Thanks for the feedback. Can you let me know what board you were trying the library on, what SD card reader you were using (if separate from the board) and what versions of Arduino and SD.h you were using. There's no buffer used in the library, it's just a wrapper for the header file. The error is related to the SD library not loading the required data from the file on the SD card into the buffer so it can send data to the lights via FastLED.

**Comment by harueg** [comment]
Hi Shaun

It was working as expected, should have connected leds first, the buffer failed to load is normal at the end of the file, it then restarts.
My bad.   Does have to read the header every time, when running the same file in a loop ?
How difficult would it be to use neopixelbus instead of fastled ?  neopixelbus supports rgbw.

Thanks a lot

Harald

**Comment by ShaunPrice** [comment]
It sounds like the file is shorter than the header is indicating. 

The library is only used to make it easy to read the FSEQ header data. Once you have the headers you can just loop over the display data. I just wrote a program that loads the file into memory in the setup routine and continuously loops over it with LED sends being triggered by a sensor.

You can you any library for the lights. I've used the neopixel library on one of my own projects. You just need to make sure the data is formatted correctly. From memory I just iterated over the data. With FastLED I could just copy the buffer straight into the library.

**Comment by ShaunPrice** [comment]
The code I mentioned that liad the data into memory is here:

https://github.com/ShaunPrice/PoV-Spinner
